FROM python:3.11.12-bookworm
# UTF-8 encoding is necessary for printing non-ASCII characters to the
# terminal.
ENV LC_ALL=C.UTF-8
# Install Poetry.
# See https://python-poetry.org/docs/#installing-with-the-official-installer
RUN POETRY_VERSION=2.1.3 && \
    cd /tmp && \
    curl -sSL https://install.python-poetry.org > install-poetry.py && \
    POETRY_HOME=/usr/local/poetry python3 install-poetry.py --version $POETRY_VERSION && \
    rm install-poetry.py
ENV PATH=/usr/local/poetry/bin:${PATH}
# Stores Python packages in the local directory.
# See https://python-poetry.org/docs/configuration/#virtualenvsin-project-boolean
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
WORKDIR /app/
