name: Run Unit Tests

on:
  push:
    branches: [ "main", "differentiable-stacks" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==2.1.3
      # See https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.12"
          cache: poetry
      - name: Install Python packages
        run: bash scripts/install_python_packages.bash
      - name: Run unit tests
        run: bash scripts/run_tests.bash
